
cloudinary:
    cloud-name: dv6ktrxwv
    api-key: 129216924887731
    api-secret: kzImAroivRAKixaSgU__grkj0AA
#paypal:
#    client:
#        id: AXwt4-s7FPgRMbtwFW93zC-__adQKck2eQdhKEVWjYAtN4_MthGzhHle45_iKwzj8El52R-rqQeUan-i
#        secret: EAydkaqDIz4i0EVOCZmG6nxH4WJm2JX32HrG6Vu4RgA9NdSza9k_yLW9Ykkexh2OrUfvn609QmXcmbdF
#    mode: sandbox
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 1
        url: jdbc:mysql://localhost:3306/hobbie_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
            use-new-id-generator-mappings: false
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
                mvc:
                    hiddenmethod:
                        enabled: true
    rsocket:
        server:
            port: 8080
            error:
                include-message: always
                include-stacktrace: never
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB





